config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  root to: "top#index"
  resources :groups, only: [:show, :edit, :update]
end

app/models/group.rb
class Group < ActiveRecord::Base

  #association
  has_many :users

end

app/models/user.rb
class User < ActiveRecord::Base

  #accessor
  attr_accessor :group_key

  #devise config
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :authentication_keys => [:email]

  #association
  belongs_to :group

   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

  def name
    "#{family_name} #{first_name}"
  end

  def name_kana
    "#{family_name_kana} #{first_name_kana}"
  end

  def full_profile?
    avatar? && family_name? && first_name? && family_name_kana? && first_name_kana?
    # 姓名、姓名カナ、画像が設定されていないとfalseを返す。カラム名 + ? と書くと、指定したカラムに値が存在しないときにfalseを返すというActiverecordの機能を利用
  end

  private
  def has_group_key?
    group_key.present?
  end

  def group_key_to_id
    group = Group.where(key: group_key).first_or_create
    self.group_id = group.id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # authenticate_user!はユーザがログインしているかどうかを確認し、ログインしていない場合はユーザをログインページにリダイレクトするdeviseのメソッド
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # sign_inのときに、group_keyも許可する
      devise_parameter_sanitizer.permit(:sign_in, keys:[:group_key])
    # sign_upのときに、group_keyも許可する
      devise_parameter_sanitizer.permit(:sign_up, keys:[:group_key])
    #account_updateのときに、group_keyも許可する
      devise_parameter_sanitizer.permit(:account_update, keys:[:group_key])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def edit
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
    params.require(:user).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_header.html.erb
<% if user_signed_in? %>
  <div class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to root_path, :class => 'navbar-brand' do %>
        <%= image_tag 'logo.png' %> <small class='hidden-xs hidden-sm'>仲間とプロフィールを共有しよう！</small>
      <% end %>
      <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'HOME', root_path %></li>
            <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">グループ <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to current_user.group.key, group_path(current_user.group) %></li>
      </ul>
    </li>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>アカウント <span class='caret'></span></a>
            <ul class='dropdown-menu' role='menu'>
            <li><%= link_to "マイページ", user_path(current_user) %></li>
            <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>

<% end %>

app/views/common/_login_logo.html.erb
<div class='sign_up_logo'>
  <%= image_tag 'logo.png' %>
  <small>仲間とプロフィールを共有しよう！</small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Profy</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <script type='text/javascript' charset='utf-8'>
      $(function(){
        $.material.init();
      });
    </script>
    <%= render partial: 'common/header' %><!--commonディレクトリ配下の_header.html.erbの部分テンプレートを呼び出す-->
    <div class='container'>
      <div class='row'>
        <div class='col-lg-12'>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
      <footer class='row text-center'>
        <p>(C) Profy 2015</p>
      </footer>
    </div>
  </body>
</html>

app/views/top/index.html.erb
<% unless current_user.full_profile? %>
  <header class="header_top panel panel-default col-lg-12 no-profile">
    <h2>まずは、あなたの基本プロフィールを登録しましょう！</h2>
    <p>Profyは友達の質問に答えながらプロフィールを作るサービスです！</p>
    <%= link_to "プロフィールを登録する", edit_user_path(current_user), { class: "btn btn-lg btn-primary withripple" } %>
  </header>
<% else %>

<% end %>

app/views/users/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for current_user do |f| %>
    <h2>プロフィール画像</h2>
      <div class="form-group file">
        <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      <h2>登録情報</h2>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name, placeholder: "姓", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          <%= f.text_field :first_name, placeholder: "名", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name_kana, placeholder: "セイ", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          <%= f.text_field :first_name_kana, placeholder: "メイ", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row form user_profile">
  <div class="col-lg-12">
    <div class="image" style="background-image: url(<%= @user.avatar.url(:medium) %>);"></div>
    <h2><%= @user.name %><span><%= @user.name_kana %></span></h2>
    <% if current_user.id == @user.id %>
      <div class="profile_edit">
        <%= link_to 'プロフィール編集', edit_user_path(current_user), {class: 'btn btn-primary withripple' }%>
      </div>
    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>